

tools:
  next-move._type: chess/tool/next-move
  eval-board._type: chess/tool/stockfish/eval-board
  eval-move._type: chess/tool/stockfish/eval-move
  draw-board._type: chess/tool/draw-board


oracle-tool._type: chess/tool/stockfish/best-move