
_base: [basic-view]

dataroot: /fast/fleeb/project_ludwig/

root: /fast/fleeb/project_ludwig/results

log-root: /fast/fleeb/project_ludwig/request-logs

stockfish-path: /fast/fleeb/project_ludwig/stockfish/stockfish-ubuntu-x86-64-avx2
