seed: 1000000009

##############

#_meta.script_name: backend
#_base: [games]

##############

_meta.script_name: eval

# _base: [demo]
#_base: [s/dp, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/zcot, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/dp, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/dpp, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/dpp, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/manual, c/vllm]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/client, c/vllm]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/format, c/vllm]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/client, c/azure]
#_base: [s/tool, ttt/tools, ttt/take-the-middle, j/client, c/vllm]

#_base: [s/dp, ttt/take-the-middle, j/format, c/vllm]
_base: [s/tool, ttt/tools, ttt/take-the-middle, j/format, c/vllm]

##############
use-chat-completion: no
#tool-style: json

#obs-rep: compact
obs-rep: desc

limit: 10

use-wandb: no

root: local_data/

viewer._type: <>broker-type
logger._type: <>broker-type
prelogger._type: <>broker-type
broker-type: min-broker

# for format judge: j/format
#style: end

#addr: http://wagner.is.localnet:8000
addr: 8003
#client.addr: 8001
#judge.addr: 8001


# resume: p6088_sfaa9_250515-120654_0b0d

#client._mod.logged: yes

#max-tokens: 1024
max-tokens: 4096 # needed for qwen3-8b due to reasoning
#max-tokens: 1024

#temperature: 0.6
#top-p: 0.95

viewer:
  _type: default-broker
  targets: <>viz
viz: {}
unviz: {}

logger:
  _type: default-broker
  targets: <>log
  untargets: <>unlog
log: {}
unlog: {}


prelogger:
  _type: default-broker
  targets: <>pre
  untargets: <>unpre
pre: {}
unpre: {}


viz:
  table:
    _type: formatter/table
    expires: 4
  score: yes
  fails: yes
  invalid: yes
  stats: yes

log:
  _all_: yes

prelog:
  _all_: yes


##################

# _base: [venice-sent, c/vllm]

# #template: venice/analysis
# template: venice/analysis-yaml

#############################
#
#_base: [1step, c/vllm]
##_base: [1step, c/openai]
##judge.template: judge-binary-nothink
#
##protocol.name: "{task.domain}-{judge.format_type}-{judge.pred_type}-{'_'.join(task.clues)}"
##protocol.name: "{task.domain}_{judge.format_type}_{judge.pred_type}_{'-'.join(task.clues)}_{now.strftime('%y%m%d-%H%M%S')}"
#
#protocol.name: "debug_{task.domain}_{judge.name}_{'-'.join(task.clues)}_{now.strftime('%y%m%d-%H%M%S')}_{unique[:4]}"
#
#
##resume: food_1step-json-prob_profile-responses-behavior_250511-133413
#
##resume: food_1step-json-prob_update2_250511-211320
#
#domain: news
##clues: [profile, responses, behavior]
#clues: [update2]
#
##zero-based: yes
##indexed: yes
#
##template: "{task_context}\n\n{question}\n/nothink"
##strategy.template: "{question}"
#
##pred-type: binary

