
_meta.script_name: eval

seed: 1000000009

#_base: [demo]


task._type: ttt/take-the-middle

strategy._type: direct-prompting

out-dir: local_data/

addr: 8000
client._type: vllm

max-tokens: 512

#template: "{task_context}\n\n{question}\n\nTake a deep breath and think step-by-step."

limit: 4
