
_meta.script_name: eval

seed: 1000000009

#_base: [demo]
#_base: [s/dp, ttt/take-the-middle, j/client]
#_base: [s/zcot, ttt/take-the-middle, j/client]
#_base: [s/dp, ttt/take-the-middle, j/client]
_base: [s/dpp, ttt/take-the-middle, j/client]

#use-wandb: no

out-dir: local_data/

addr: 8001
client._type: vllm

judge.addr: 8000

max-tokens: 1024

