
clients:
  - 8001
  - 8002
  - 8003

judge: 8001
judge-continue: no

players:
  direct:
#    tictactoe: {_type: ttt/simple, judge-template: game/ttt/judge}
    tictactoe: {_type: ttt/simple, judge-template: null}
#    chess: {_type: chess/simple}

