_base: [s/dp]
project-name: venice-analysis
seed: 1000000009
#protocol.name: "{task.domain}-{judge.format_type}-{judge.pred_type}-{'_'.join(task.clues)}"
out-dir: local_data/
log-samples: yes
#limit: 2
#max-tokens: 1024
protocol.name: "p{strategy.template.code[:4]}_s{judge.schema.code[:4]}_{now.strftime('%y%m%d-%H%M%S')}_{unique[:4]}"
##################################


temperature: 0.6
top-p: 0.95

judge._type: json-judge
max-tokens: 1024

template: venice/analysis

##################################
use-wandb: no

dataroot: C:\Users\anwan\OneDrive\Khan\research\recoreact\data
task._type: venice-analysis
drop-keys:
  - table.prompt

