_base: [s/dp]
project-name: venice
seed: 1000000009
#protocol.name: "{task.domain}-{judge.format_type}-{judge.pred_type}-{'_'.join(task.clues)}"
out-dir: local_data/
#limit: 2
#max-tokens: 1024
protocol.name: "{task.domain}_{judge.name}_{'-'.join(task.clues)}_{now.strftime('%y%m%d-%H%M%S')}"
##################################

temperature: 0.6
top-p: 0.95

domain: travel

#clues: [behavior]
clues: [profile, responses, behavior]

format-type: json
#format-type: jsonblock
#format-type: yamlblock

#pred-type: 5point
pred-type: prob
#pred-type: binary

indexed: yes

zero-based: no


##################################
use-wandb: no

dataroot: C:\Users\anwan\OneDrive\Khan\research\recoreact\data
task:
  _type: venice
  template: venice/bounds

